MAX_SEQUENCE_LENGTH = 20

SECONDS_IN_DAY = (60 * 60 * 24)

WORDS_AMOUNT_TO_RELEARN = 10

MIN_DELTA_TIME = 0.1

HISTORY_CORRECT_THRESHOLD = 10

TIME_DELTA_THRESHOLD = 14

LEVEL_ORDER = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2']
